env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  main: ./cmd/containerd-healthcheck/main.go
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    linux: Linux
    amd64: x86_64
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
