---
containerd:
  socket: /run/containerd/containerd.sock
  namespace: services.linuxkit
checks:
  - container_task: hello-world-api
    http:
      url: http://127.0.0.1:3000
      expected_body: Hello
    timeout: 1
    execution_period: 4
    initial_delay: 10
    restart_delay: 10
    threshold: 3
  - container_task: google
    http:
      url: https://www.google.com
    timeout: 1
    execution_period: 2
    initial_delay: 2
    threshold: 3
