---
containerd:
  socket: /run/containerd/containerd.sock
  namespace: default
checks:
  - container_task: google
    http:
      url: https://www.google.com
    timeout: 1
    execution_period: 2
    initial_delay: 2
    threshold: 3
