name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker run --rm --privileged tonistiigi/binfmt --install all
        docker buildx create --name arm-builder --platform arm64 --use
        docker buildx build --load --builder arm-builder --platform linux/arm64 .
